language: python

# Specify Python versions
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - COVERALLS_PARALLEL=true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest coveralls
  - pip freeze

# command to run tests
script:
  - coverage run -m --source=. pytest
  - coveralls
# Push the results back to coveralls
after_success:
  - coveralls
